--- 
chdir: /home/deploy/www/yuccamagazine/current
environment: production
address: 0.0.0.0
port: 5000
timeout: 30
log: /home/deploy/www/yuccamagazine/shared/log/thin.log
pid: /home/deploy/www/yuccamagazine/shared/pids/thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []

wait: 30
servers: 1
daemonize: true
